[admin.editor]
login=admin
password=48bb366d350e7d5b84e5c8f4b198398e

login=developer
password=48bb366d350e7d5b84e5c8f4b198398e

;для активации режима многих пользователей (нескольких администраторов) этот раздел необходимо раскомментировать
;[admin.users]
;enabled=yes

[admin.leftmenu]
pages "Текстовые страницы"
seoparams "Страницы SEO"
/admin/edit/options/all "Опции"
products "Часы"
products__fields "Свойства часов"
rubrics Рубрики
news Новости
collections Коллекции
faq_categories "Категории вопросов-ответов"
faqs "Вопросы-ответы"
collections_mains "Коллекции на главной"
sliders "Слайдеры на главной"
packs "Упаковки"

;режим нескольких администраторов
;admin_users "Администраторы системы"