[admin.editor]
login=admin
password=6d371ca7d720d1cfbf7ccb6c06a9b404

login=developer
password=48bb366d350e7d5b84e5c8f4b198398e

;для активации режима многих пользователей (нескольких администраторов) этот раздел необходимо раскомментировать
;[admin.users]
;enabled=yes

[admin.leftmenu]
pages "Текстовые страницы"
seoparams "Страницы SEO"
cities "Города"
collections Коллекции
products "Продукты"
products__fields "Свойства продуктов"
categories "Категории продуктов"
rubrics Рубрики
news Новости
faq_categories "Категории вопросов-ответов"
faqs "Вопросы-ответы"
;collections_mains "Коллекции на главной"
;sliders "Слайдеры на главной"
products_variants "Упаковки"
workshops "Мастерские"
saleshops "Офисы продаж"
delivery_variants "Варианты доставок"
orders "Заказы"
reviews "Отзывы"
;menu_main_elements "Элементы меню"
;menu_elements "Подэлементы меню"
importlogs "Логи импорта"
feedbacks "Сообщения с сайта"
/admin/edit/options/all "Опции"
;main_banners "Баннеры на главной"
;режим нескольких администраторов
;admin_users "Администраторы системы"