[feedback_form.call]
title=Сообщение с сайта

[feedback_form.consultation]
title=Сообщение с сайта

[feedback_form.question]
title=Сообщение с сайта

[feedback_form.order]
title=Заказ с сайта

[feedback_form.review]
title=Отзыв с сайта
redirect=/thankyou-reviews
;success_message=Наши специалисты свяжутся с Вами в кратчайшие сроки
tables.reviews=name
tables.reviews=email
tables.reviews=text
tables.reviews=product_id
tables.reviews.published_at=NOW


;success_message=Спасибо<br>Наши специалисты свяжутся с Вами в кратчайшие сроки
;[feedback_form.reservation]
;title=Бронирование столика на сайте
;redirect=/thanks-for-reservation
;fields=name
;fields=phone
;fields=persons_number
;fields=comment
;fields=restaurants_table_id
;fields=url

