[smart_antispam]
;Не принимать, если клиент не сумел выполнить javascript.
;В форму необходимо вставить код {{smart_antispam_javascript}}
;В валидатор надо вставить smart_antispam.message=Ваше сообщение похоже на спам
validate_javascript=yes


;Не принимать, если не пришёл AJAX (Xmlhttprequest)
validate_ajax=yes

