[admin.fields]
;small url "Адрес" "(необязательно)"
small subdomain "Поддомен"
small title "Название"
small second_title "Название для генерации"
small phone "Телефон"
;big phones "Все телефоны"
small contact_email "E-mail"
small address "Адрес офиса"
;small post_address "Почтовый адрес"
small coords "Координаты на карте"
;big requisites "Реквизиты"
small work_time "Часы работы"
;big contacts_text "Контакты" html
;rich text "Текст"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

;[admin.use_model]
;source=d()->Page
;sort=yes
;list=yes
;edit=yes

[admin.columns]
title=Название
;phone=Телефон
subdomain=Поддомен
;kladr_title=Исходное название
;page_url=Адрес
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
