[admin.fields]
big comment "Комментарий<br>(не используется)"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

[admin.use_model]
;source=d()->Page
;sort=yes
list=yes
;edit=yes

[admin.columns]
created_at=Дата
show_import_type=Действие
;show_category=Категория
show_file=Файл
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
