[admin.fields]
;urltranslit url "Адрес (URL)" title
small link "Адрес (URL)"
big old_urls "Старые адреса"
small title "Название"
;checkbox show_main "Отображать на главной"
;checkbox show_header "Отображать в шапке"
image image "Обложка при отображении на главной (240x370 px)"
;rich text "Описание для баннера категории"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

;[admin.use_model]
;source=d()->Page
;sort=yes
;list=yes
;edit=yes

[admin.columns]
;url=Адрес
title="Название"
show_main="Отображать на главной"
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
;list.sort_field=created_at
;list.sort_direction=desc
