[admin.fields]
legend "Контактная информация "
small feedback_email "E-mail для сообщений с сайта"
small contact_email "E-mail (контактный)"
small number "Номер для связи"
small work_time "Режим работы в контактах"
small address "Адрес"
legend "Ссылкы на соцсети "
small link_vk "Ссылка на вк"
small link_facebook "Ссылка на фейсбук"
small link_instagramm "Ссылка на инстаграмм"
legend "Сайт "
small common_title "Название сайта"
rich footer_description "Описание в футере сайта"
legend "Блок Новинка "
chosen_table_single product_id "Новый продукт для блока Новинка" products
image image_new "Обложка нового продукта (400x278 px)"
legend "Баннер в каталоге "
image image_catalog_banner "Обложка баннера в каталоге (1140x160 px)"
small title_catalog_banner "Заголовок баннера в каталоге"
small description_catalog_banner "Описание баннера в каталоге"
small link_catalog_banner "Ссылка с баннера"

;catalog_import
;small phone "Телефон"
;big phones "Все телефоны"
;small email "E-mail"
;small address "Адрес"
;small post_address "Адрес с индексом"
;small coords "Координаты на карте"
;big requisites "Реквизиты"
;big working_hours "Часы работы"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

;[admin.use_model]
;source=d()->Page
;sort=yes
;list=yes
;edit=yes

;[admin.columns]
;page_url=Адрес
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
;list.sort_field=created_at
;list.sort_direction=desc
