[admin.fields]
small feedback_email "E-mail для сообщений с сайта"
small number "Номер для связи"
small address "Адрес"
small en_address "Адрес на английском"
small common_title "Название сайта"
small en_common_title "Название сайта на английском"
rich footer_description "Описание в футере сайта"
rich en_footer_description "Описание в футере сайта на английском"
chosen_table_single product_id "Новый продукт для блока Новинка" products
image image_new "Обложка нового продукта"
image en_image_new "Обложка нового продукта на английском"
small delivery_free_min_price "Минимальная цена для бесплатной доставки"
rich delivery_free_text "Текст бесплатной доставки на странице товара"
rich en_delivery_free_text "Текст бесплатной доставки на странице товара"

legend "Баннер в каталоге"
small title_catalog_banner "Заголовок"
small en_title_catalog_banner "Заголовок на английском"
small description_catalog_banner "Описание"
small en_description_catalog_banner "Описание на английском"
image image_catalog_banner "Изображение"
image en_image_catalog_banner "Изображение на английском"
small link_catalog_banner "Ссылка"

catalog_import

legend "Настройки СЕО"
big robots_txt "robots.txt"

legend "Кнопки социальных сетей"
small link_vk "VK"
small link_facebook "Facebook"
small link_instagramm "Instagram"

;small phone "Телефон"
;big phones "Все телефоны"
;small email "E-mail"
;small address "Адрес"
;small post_address "Адрес с индексом"
;small coords "Координаты на карте"
;big requisites "Реквизиты"
;big working_hours "Часы работы"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

;[admin.use_model]
;source=d()->Page
;sort=yes
;list=yes
;edit=yes

;[admin.columns]
;page_url=Адрес
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
;list.sort_field=created_at
;list.sort_direction=desc
