[admin.fields]
select status_id "Статус" "Новый(1)" "Обрабатывается(2)" "Отправлен(3)" "Получен(4)" "Закрыт(5)" "Отменён(6)" 
;chosen_table_single delivery_type_id "Способ доставки"
;small delivery_name "Способ доставки"
;select payment_option "Способ оплаты" "Наличными курьеру(cash)" "Онлайн пластиковой картой(sber)"

;small track_number "Трек-номер"
control_flag orders_status_change_mail "Отправить оповещение о смене статуса"
;legend "Воспользуйтесь API"

;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

[admin.addbuttons]
/order_products/ Подробнее
;/list/order_products/order_id/ Товары
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

[admin.use_model]
source=d()->Order->where('`status_id` is not null')->order('`ordered_at` desc')
;sort=yes
list=yes
;edit=yes

[admin.columns]
show_status_id=Статус
;show_payment_status=Онлайн-оплата
created_at=Дата создания
products_price=Стоимость товаров
order_price=Стоимость заказа
;show_user=Пользователь
name=Имя
phone=Телефон
email=E-mail
comment=Комментарий
pay_info=Тип и статус оплаты
;payed_amount=Оплачено

;payed_amount=Оплачено
;show_is_payed=Оплата


;page_url=Адрес
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
