[admin.fields]
small title "Название"
small unit "Единица измерения" "(не обязательно)"
;hidden type "Тип" ""
select type "Тип" "Строка()" "Несколько строк(strings_list)" "Признак(boolean)" "Число(number)" "Диапазон(range)"
checkbox is_filter "Фильтр"
select sort_type "Сортировать по" "Количеству()" "Значению(natural)" "Числовому значению(number)"
checkbox is_in_short_list "Показать в кратком списке"
checkbox is_in_preview "Показать в списке товаров"

container_begin type "boolean"
small title2 "Название для генерации"
container_end
container_begin type "" deletable
big variants "Значения для генерации"
small value_template "Шаблон для генерации"
container_end
container_begin type "strings_list" deletable
big variants "Значения для генерации"
container_end

[admin.use_model]
paginator=10000
list=yes

[admin.columns]
title=Название
field_name=Имя поля
