[admin.fields]
urltranslit url "Адрес (URL)" title
big old_urls "Старые адреса"
small title "Название"
small price Цена
small discount "Цена со скидкой"
checkbox is_interesting "Выводить в возможно вас заинтересует"
checkbox is_top "Выводить в хитах продаж"
rich text "Краткое описание"
rich text_full "Подробное описание"
image image "Изображение" galleries 180 auto
chosen_table_single collection_id "Коллекция" collections
rich text_props "Свойства часов"
all__fields
;date posted_at Дата
;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

;[admin.use_model]
;source=d()->Page
;sort=yes
;list=yes
;edit=yes

;[admin.columns]
;page_url=Адрес
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
;list.sort_field=created_at
;list.sort_direction=desc

[admin.use_model]
paginator=10000
sort=yes
list=yes

[admin.sortoptions]
title=admin_sort_title
