[admin.fields]
urltranslit url "Адрес" title
date published_at "Дата"
small name "Имя"
rich text "Отзыв"
checkbox is_published "Опубликовать на сайте"


;userdate date Дата
;image image "Изображение" galleries 180 auto
;file file  Файл "files"
;select razdel Раздел "Оборудование(1)" "Обучение(2)"
;checkbox is_active "Активный?"

;<тип поля> <имя поля> <название для администратора>

;[admin.addbuttons]
;/list/texts/	Подстраницы
;/list/goods/catalog_id/   "Связанные товары"

[admin.use_model]
;source=d()->Page
;sort=yes
list=yes
;edit=yes

[admin.columns]
;page_url=Адрес
name=Имя
email=E-mail
published_at=Дата
show_is_published=Опубликован
;title=TITLE
;multi_domain = Домен

;[admin]
;urlredirect=/
;list.sort_field=created_at
;list.sort_direction=desc
