[admin.fields]
small page_url "URL страницы"
big old_urls "Старые адреса"
small title "Title"
small description "Description"
small keywords "Keywords"


;multi

rich h1 "H1"
rich text "Текст в подвале"
 
[admin.bottombuttons]

/list/seoparams/page_url/*	"Страница по-умолчанию"


[admin.columns]
page_url=Адрес
title=Title
;multi_domain = Домен